### ISSUE TITLE
USER STORY: As an admin, I want to view all user accounts, so that I can monitor activity and handle issues if needed

### ISSUE THREAD

**Issue by AshLaw96** [AshLaw96/Nomad-Nation#13]
EPIC: View all user accounts

As a **admin**, I can **view all user accounts**, so that **I can monitor activity and handle issues if needed**.

**Acceptance Criteria**
- [ ] Admins can log in to an admin dashboard.
- [ ] Admins can view a list of all user accounts with key details (e.g. username/email, account creation date, last login, role etc).
- [ ] Admins can search and filter user accounts (e.g., by username, email, role, or activity status).
- [ ] Admins can see additional details for a specific user (e.g. booking history, reviews/comments, number of caravan listed if an owner).
- [ ] Admins can flag or deactivate problematic accounts.
- [ ] Deactivated accounts cannot log in or perform actions on the app.

**Tasks**
- [ ] Task 1: Set up admin only dashboard access
- [ ] Task 2: Create user account views (e.g. implement an endpoint to fetch user account data and add filters and search functionality for specific fields)
- [ ] Task 3: Add detailed view that shows a user's profile, booking history, and contributions (e.g. reviews, caravan listings)
- [ ] Task 4: Add a field to mark accounts as deactivated
- [ ] Task 5: Prevent deactivated users from logging in or making changes
- [ ] Task 6: Design admin user list page (e.g. display user accounts in a table with sort-able columns and add a search bar and filter drop-down)
- [ ] Task 7: Design a user details page (e.g. display account specific details and add a deactivate account button)
- [ ] Task 8: Show confirmation messages for actions like account deactivation or reactivation
- [ ] Task 9: Write tests (e.g. fetching user account data, filtering/searching user accounts and deactivation logic)
