### ISSUE TITLE
USER STORY: As a caravan owner, I want to create a listing for my caravan, so that I can rent it out to customers

### ISSUE THREAD

**Issue by AshLaw96** [AshLaw96/Nomad-Nation#4]
EPIC: Listing a caravan

As a **caravan owner** I can **create a listing for my caravan** so that **I can rent it out to customers**.

**Acceptance Criteria**
- [x] Owners can fill out the caravan listing form (e.g. title, description, pricing, features, etc).
- [x] The form validates all required fields.
- [x] When submitted it is visible to users.
- [x] Owners can view and edit their listings.

**Tasks**
- [x] Task 1: Create a caravan owner model with relevant fields
- [ ] Task 2: Add permissions to restrict listing creation to owners
- [x] Task 3: Create view for adding new caravans.
- [ ] Task 4: Write tests for caravan creation and permission handling
- [x] Task 5: Design a form for creating caravan listings
- [x] Add fields for caravan details
- [x] Add input validation for required fields
- [x] Link front-end form to the back-end caravan creation view
- [ ] Write tests for caravan creation
- [ ] Test for edge cases
