### ISSUE TITLE
USER STORY: As a user, I want to receive a confirmation email or notification for my booking, so that I have proof and details of my reservation

### ISSUE THREAD

**Issue by AshLaw96** [AshLaw96/Nomad-Nation#7]
EPIC: Receive confirmation of booking

As a **user**, I can **receive a confirmation email or notification for my booking** so that **I have proof and details of my reservation**.

**Acceptance Criteria**
- [ ] A confirmation email is sent to the user immediately after booking is successfully completed.
- [ ] The email can include caravan name and description, booking ID, reservation dates, total price, cancellation policy and contact information.
- [ ] If notifications are enabled, the user receives an in-app notification with the same booking details.
- [ ] After completing a booking, the user is redirected to confirmation page displaying booking details.
- [ ] The page includes a message informing the user than an email or notification has been sent.

**Tasks**
- [ ] Task 1: Configure Django's email back-end
- [ ] Task 2: Create an email template for booking confirmations using Django's templates
- [ ] Task 3: Implement an email-sending function that triggers after a successful booking
- [ ] Task 4: Pass booking details to the email template
- [ ] Task 5: If in-app notifications are enabled, create a notification model with fields
- [ ] Task 6: Add a function to generate a new notification for the booking
- [ ] Task 7: Write tests for the email sending function (e.g. ensuring the email is sent to the correct user and that the email includes all the correct booking details)
- [ ] Task 8: Design confirmation email template
- [ ] Task 9: Design a confirmation page with the same information as the email
- [ ] Task 10: Add a confirmation message informing the user an email has been sent
- [ ] Task 11: Design a model popup for the in-app notification
- [ ] Task 12: Create a view booking details link in the users dashboard that takes them to a booking detail page
- [ ] Task 13: Verify that the booking confirmation triggers the correct email or notification
- [ ] Task 14: Write tests to verify that the email or notification works correctly
